version: '3'
services:
  ex0bot:
    build: .
    restart: unless-stopped
    environment:
      - 'PYTHONUNBUFFERED=1'
  redis-server:
    image: 'redis'
    environment:
      - "REDIS_ARGS=--save 300 1"
    volumes:
      - $PWD/redis_data:/data
