version: '3'
services:
  ex0bot:
    build: ./bot
    restart: unless-stopped
    # environment:
    #  - REDIS_URL="redis://redis-server:6379"
  redis-server:
    image: 'redis'
    volumes:
      - $PWD/redis_data:/data
